### ISSUE TITLE
No output files after running the command and log file is blank 

### ISSUE THREAD

**Issue by Anees-caas** [aziele/pfam_scan#5]
Dear sir, I am running a command to identify the lncRNAs; after the command, I am not sure if my command is running or not because on the terminal I am not getting error, the login files are coming out blank, and initially I am not getting and output files e.g csv
./pfam_scan.pl -fasta /protein.fasta  -dir /lncRNA/pfamdb -out /lncRNA/Pfam_scan.out >/lncRNA/Pfam_scan.log 2>&1

**Comment by aziele** [comment]
The `pfam_scan.pl` tool is specifically designed to identify protein domains by analyzing protein sequences against the Pfam database. Since long noncoding RNAs (lncRNAs) do not encode proteins, they typically lack conserved protein domains, making `pfam_scan.pl` unsuitable for lncRNA analysis.

Please note that I am not the developer of `pfam_scan.pl`, which is officially supported by Pfam. My repository provides `pfam_scan.py`, a separate implementation.
